### ISSUE TITLE
Many patches have be rewritten

### ISSUE THREAD

**Issue by SeungheonOh** [dylanaraps/sowm-patches#1]
Most of patches have to be rewritten due to the major structure change of sowm(new header file)

**Comment by dylanaraps** [comment]
@Leon-Plickat

**Comment by dylanaraps** [comment]
@AnusReaper

**Comment by reciate** [comment]
RMA'd my only Linux machine but I can get on it pretty soon.

**Comment by Leon-Plickat** [comment]
Since there is need to update the patches, this would also be a good time to index and document them. Currently all people will see is a directory with a bunch of vaguely named `*.patch` files in it. One can not expect users to read the source of every patch just to know what feature it is providing. Therefore a patch-index is needed; Maybe a "Name | Author | Description" table in the `README`?

**Comment by dylanaraps** [comment]
READ: https://github.com/dylanaraps/sowm/pull/57
